### PR TITLE
Kismet Server on Kuberenetes

### PR DESCRIPTION
**Pull request by sketchybinary**
I've been working on running kismet on Kubernetes for a little while in my own repo and I'd like to start contributing some of my changes back.

These changes are the first steps towards getting an automated build of kismet for docker out there, so that users don't need to build the kismet server themselves.  Run ```sudo docker run -it quay.io/sketchybinary/kismet:latest /bin/bash``` to see my container. 

The Dockerfile builds the Kismet project that is currently checked out by the builder in git, instead of cloning it down.  This allows you to update the code on your local machine and rebuild it immediately, without merging it into master on github.

The tricky thing that this commit does, is break out the build process into two [stages](https://docs.docker.com/develop/develop-images/multistage-build/).  This allows us to separate the source code and build dependencies from the runtime dependencies.  This reduced the image by almost 50%.  I only run this as a server fed by remote sensors, so I haven't tested very much of this yet.

The Kubernetes portion is simple: It opens up a ingress mapping at kismet.localhost (you can customize this with whatever domain you ingress uses) and maps it to 2501 on the container, it opens up 3501 on a loadbalancer and maps that to the api port on the container, it creates a pvc (persistent storage) and maps it to the container, then it starts the container using my image in quay.io.

I can help you get an official docker or quay build going as well, I think the community would benefit.

Please let me know if you have any questions, this is a lot to take in if you haven't done kubernetes or containers much.

I did a writeup on setting up k3s and running kismet in my original branch.  I'm not sure how much of that we want to put into the README here though. https://github.com/sketchybinary/kismet/blob/kismet-2019-07/packaging/k8s/README

### CODE REVIEW

**Comment by kismetwireless** [comment]
Looks like the comments I had put on didn't make it through; sorry!

First comment - I just moved the python tools to python3 this week, which will probably take a little care and feeding to update.

Second comment - maybe I don't understand the patches, but it looks like this expects the build to happen on the host, and not in the docker image, now?  Won't that cause problems for anyone who isn't building on the exact same OS as the docker image?

**Comment by sketchybinary** [comment]
Sorry, I've been really busy the last few days.  I'll update it to use python3, no problem.

The build still happens inside the docker container, it just builds the currently checked out branch.  This lets you build containers for branches or even uncommitted changes, instead of just master.  If we get these patches in, I'd like to work with you to setup an official docker image on a publicly hosted repo.  Are you going to be at DEFCON?

**Comment by sketchybinary** [comment]
Should I be targeting master here?  I've been rebasing this onto your master branch

**Comment by kismetwireless** [comment]
Yeah working off master is a good target; now that py3 is in I'm not expecting any major changes to the deps in the near future.

**Pull request closed without merging**
